const products = [
  {
    "id": "1",
    "topdeal": true,
    "price": "69.99",
    "discount": 72,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["Free Shipping", "New", "20 Days 08:20:00"],
  },
  {
    "id": "2",
    "topdeal": false,
    "price": "69.99",
    "discount": 68,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["Free Shipping"],
  },
  {
    "id": "3",
    "topdeal": false,
    "price": "69.99",
    "discount": 66,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["Free Shipping", "New"],
  },
  {
    "id": "4",
    "topdeal": false,
    "price": "69.99",
    "discount": 45,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["Free Shipping", "New", "03:45:27"],
  },
  {
    "id": "5",
    "topdeal": false,
    "price": "69.99",
    "discount": 40,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["New"],
  },
  {
    "id": "6",
    "topdeal": false,
    "price": "69.99",
    "discount": 57,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["Free Shipping", "New"],
  },
  {
    "id": "7",
    "topdeal": false,
    "price": "69.99",
    "discount": 65,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["Free Shipping", "10 Days 04:12:51"],
  },
  {
    "id": "8",
    "topdeal": false,
    "price": "69.99",
    "discount": 47,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["New", "08:20:00"],
  },
  {
    "id": "9",
    "topdeal": false,
    "price": "69.99",
    "discount": 60,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["Free Shipping"],
  },
  {
    "id": "10",
    "topdeal": true,
    "price": "69.99",
    "discount": 80,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["New", "10 Days 04:12:51"],
  },
  {
    "id": "11",
    "topdeal": false,
    "price": "69.99",
    "discount": 45,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["12:37:11"],
  },
  {
    "id": "12",
    "topdeal": false,
    "price": "69.99",
    "discount": 58,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["New", "Free Shipping"],
  },
  {
    "id": "13",
    "topdeal": false,
    "price": "69.99",
    "discount": 55,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["Free Shipping"],
  },
  {
    "id": "14",
    "topdeal": false,
    "price": "69.99",
    "discount": 49,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["Free Shipping", "New", "07 Days 01:41:29"],
  },
  {
    "id": "15",
    "topdeal": false,
    "price": "69.99",
    "discount": 41,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["New", "04:12:51"],
  },
  {
    "id": "16",
    "topdeal": false,
    "price": "69.99",
    "discount": 63,
    "text": "Stand mixer with extra power handle ppreciation Gift Basket My Chu..",
    "retail": "Amazon",
    "specials": ["New"],
  }
];

export default products;
